name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    name: Generate APK and SHA-1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: "17"

      - name: Set execution flag for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Ensure APK path exists
        run: |
          if [ ! -f app/build/outputs/apk/debug/app-debug.apk ]; then
            echo "APK not found, build may have failed."
            exit 1
          fi

      - name: Generate SHA-1 checksum
        run: sha1sum app/build/outputs/apk/debug/app-debug.apk > checksum.sha1

      - name: Ensure checksum file exists
        run: |
          if [ ! -f checksum.sha1 ]; then
            echo "Checksum file not found, generation may have failed."
            exit 1
          fi

      - name: Upload APK and checksum
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            checksum.sha1
